### ISSUE TITLE
Release needs to be added to the manifest (steps missing in README)

### ISSUE THREAD

**Issue by SalamatKhan** [shieldproject/shield-addon-bbr-boshrelease#2]
The documentation is not accurate. Adding the following job without adding the release does not work:
instance_groups:
  - name: whatever
    jobs:
      # ...
      - name:    shield-addon-bbr-1.1.4
        release: shield-addon-bbr

Add the following steps as well:
relesaes:

- name: shield-addon-bbr
  version: latest

**Comment by bgandon** [comment]
Hi,
I submitted PR #3 for this.
Next time, please submit a PR.
Best

**Comment by ramonskie** [comment]
PR is merged
