### ISSUE TITLE
Error streaming backup from remote instance. Error: ssh.Stream failed: stdout.Write failed

### ISSUE THREAD

**Issue by Klojo** [shieldproject/shield-addon-bbr-boshrelease#4]
Running backup task (using bzip2 compression)
=============================================
bbr plugin starting up...
[bbr] 2019/03/05 14:20:10 INFO - Looking for scripts
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/blobstore/backup
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/blobstore/restore
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/credhub/post-backup-unlock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/credhub/post-restore-unlock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/credhub/pre-backup-lock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/credhub/pre-restore-lock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/director/backup
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/director/restore
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/uaa/post-backup-unlock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/uaa/post-restore-unlock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/uaa/pre-backup-lock
[bbr] 2019/03/05 14:20:10 INFO - bosh/0/uaa/pre-restore-lock
[bbr] 2019/03/05 14:20:10 INFO - Running pre-checks for backup of 10.113.48.129...
[bbr] 2019/03/05 14:20:10 INFO - Starting backup of 10.113.48.129...
[bbr] 2019/03/05 14:20:10 INFO - Running pre-backup-lock scripts...
[bbr] 2019/03/05 14:20:10 INFO - Locking uaa on bosh/0 for backup...
[bbr] 2019/03/05 14:20:10 INFO - Locking credhub on bosh/0 for backup...
[bbr] 2019/03/05 14:20:10 INFO - Finished locking uaa on bosh/0 for backup.
[bbr] 2019/03/05 14:20:11 INFO - Finished locking credhub on bosh/0 for backup.
[bbr] 2019/03/05 14:20:11 INFO - Finished running pre-backup-lock scripts.
[bbr] 2019/03/05 14:20:11 INFO - Running backup scripts...
[bbr] 2019/03/05 14:20:11 INFO - Backing up blobstore on bosh/0...
[bbr] 2019/03/05 14:20:11 INFO - Finished backing up blobstore on bosh/0.
[bbr] 2019/03/05 14:20:11 INFO - Backing up director on bosh/0...
[bbr] 2019/03/05 14:20:12 INFO - Finished backing up director on bosh/0.
[bbr] 2019/03/05 14:20:12 INFO - Finished running backup scripts.
[bbr] 2019/03/05 14:20:12 INFO - Running post-backup-unlock scripts...
[bbr] 2019/03/05 14:20:12 INFO - Unlocking uaa on bosh/0...
[bbr] 2019/03/05 14:20:12 INFO - Unlocking credhub on bosh/0...
[bbr] 2019/03/05 14:20:12 INFO - Finished unlocking uaa on bosh/0.
[bbr] 2019/03/05 14:20:13 INFO - Finished unlocking credhub on bosh/0.
[bbr] 2019/03/05 14:20:13 INFO - Finished running post-backup-unlock scripts.
[bbr] 2019/03/05 14:20:13 INFO - Copying backup -- 3.1M uncompressed -- from bosh/0...
[bbr] 2019/03/05 14:20:13 INFO - Copying backup -- 18G uncompressed -- from bosh/0...
[bbr] 2019/03/05 14:20:13 INFO - Finished copying backup -- from bosh/0...
[bbr] 2019/03/05 14:20:13 INFO - Starting validity checks -- from bosh/0...
[bbr] 2019/03/05 14:20:13 INFO - Finished validity checks -- from bosh/0...
[bbr] 2019/03/05 14:21:21 INFO - Backup created of 10.113.48.129 on 2019-03-05 14:20:13.064696668 +0000 UTC m=+2.420825305
[bbr] 2019/03/05 14:21:21 INFO - Cleaning up...
1 error occurred:
error 1:
1 error occurred:
error 1:
Error streaming backup from remote instance. Error: ssh.Stream failed: stdout.Write failed

we have in the bbr addon on shield deployment, the brr v1.2.4 replaced for the new version of bbr v1.4.0. and it's working now!

can you make a new release with the new bbr version 1.4.x 
The versions between v1.2.4/v1.4.x are many bug fixxes....

**Comment by jhunt** [comment]
Thanks for tracking that down @Klojo; we'll try to get a new addon release out with updated BBR tooling.

**Comment by jhunt** [comment]
released in 0.2.0: https://github.com/shieldproject/shield-addon-bbr-boshrelease/releases/tag/v0.2.0

Enjoy!

**Comment by patjones** [comment]
Hey @Klojo. We had to quickly switch the order of a chmod in the packaging script for bbr. A new release should be out soon.

**Comment by jhunt** [comment]
Fixed the chmod issue in 0.2.0, with 0.2.1: https://github.com/shieldproject/shield-addon-bbr-boshrelease/releases/tag/v0.2.1
